site_name: Loonybot Documentation
site_url: https://www.loonybot.com/

theme:
  name: material

nav:
  - Home: index.md

plugins:
  - search

remote_url: https://github.com/loonybot/loonybot.github.io.git

